# Generated by Django 3.2.8 on 2021-10-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='name_reporter',
            field=models.CharField(default='', max_length=20),
        ),
    ]
