# Generated by Django 3.2.8 on 2021-10-29 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_house_name_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_property', models.TextField(blank=True, default='', max_length=200)),
                ('outside_property', models.TextField(blank=True, default='', max_length=200)),
                ('have_wifi', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house')),
            ],
        ),
    ]
